### ISSUE TITLE
Whether need to set DRONE_AGENTS_ENABLED for server configuration in multi-machine?

### ISSUE THREAD

**Issue by leafney** [go-training/drone-tutorial#3]
The drone for 1.x Multi-Machine document is :
```
docker run \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  --volume=/var/lib/drone:/data \
  --env=DRONE_GITHUB_SERVER=https://github.com \
  --env=DRONE_GITHUB_CLIENT_ID={% your-github-client-id %} \
  --env=DRONE_GITHUB_CLIENT_SECRET={% your-github-client-secret %} \
  --env=DRONE_AGENTS_ENABLED=true \
  --env=DRONE_RPC_SECRET={% your-shared-secret %} \
  --env=DRONE_SERVER_HOST={% your-drone-server-host %} \
  --env=DRONE_SERVER_PROTO={% your-drone-server-protocol %} \
  --env=DRONE_TLS_AUTOCERT=true \
  --publish=80:80 \
  --publish=443:443 \
  --restart=always \
  --detach=true \
  --name=drone \
  drone/drone:1
```

But the `--env=DRONE_AGENTS_ENABLED=true` not find in your docker-compose.yml. Is this necessary?
Thanks.

**Comment by fgimian** [comment]
I also have looked for this everywhere and in the source and see no reference so I'm going to remove it.  It is mentioned in the [GitLab guide](https://readme.drone.io/installation/providers/gitlab/) but as mentioned above, it's not in the config reference.

**Comment by appleboy** [comment]
DRONE_AGENTS_ENABLED as `true` if you want to run server and agent in the same container.

**Comment by Hassanzadeh-sd** [comment]
you can use this compose file :
https://gist.github.com/Hassanzadeh-sd/db77265925507405a1ce2cacf5a77e03
